version: '3'

services:
  db:
    container_name: mangareader_pg
    hostname: pg.mangareader.com
    image: postgres:14-alpine
    environment:
      PGUSER: "mangareader" #Variável pré-definir o usuário da ferramenta psql.
      POSTGRES_USER: "mangareader"
      POSTGRES_PASSWORD: "manga@Reader2022"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 
    networks:
      - mangareader

networks: 
  mangareader:
    driver: bridge