spring:

    datasource:
        url: jdbc:postgresql://pg.mangareader.com:5432/mangareader
        username: mangareader
        password: manga@Reader2022

    jpa:
        show-sql: true
        properties:
            hibernate:
                '[format_sql]': false
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none

application:
    security:
        rememberme:
            key: sdaskjhgs09834uidhfgsldjkth34098sdfglkjb54lkjjhjhgsd034lkjhsdg-dfsjh328
            validity-days: 21
            cookie-name: JREMEMBERME