spring:

    datasource:
        url: jdbc:postgresql://pg.mangareader.com:5432/mangareader
        username: mangareader
        password: manga@Reader2022

    jpa:
        show-sql: false
        properties:
            hibernate:
                '[format_sql]': false
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update

application:
    security:
        rememberme:
            key: ${MANGAREADER_REMEMBERME_VALIDITY:kasjhd0aufdg37qyrsdfghaslkgjy23rsadgasdgasdfsdf}
            validity-days: ${MANGAREADER_REMEMBERME_VALIDITY:21}
            cookie-name: ${MANGAREADER_REMEMBERME_COOKIE_NAME:JREMEMBERME}