spring:

    datasource:
        url: jdbc:postgresql://127.0.0.1:5432/mangareader
        username: mangareader
        password: manga@Reader2022

    jpa:
        show-sql: false
        properties:
            hibernate:
                '[format_sql]': false
                dialect: org.hibernate.dialect.PostgreSQLDialect
            # javax:
            #     persistence:
            #         schema-generation:
            #             scripts:
            #                 create-target: create.sql
            #                 action: create
        hibernate:
            ddl-auto: update

application:
    security:
        rememberme:
            key: askjfhsldkjahlafkjhlgkjh983405dfgdfsgsjh
            validity-days: 21
            cookie-name: JREMEMBERME